[package]
name = "componsition_lang" # the name of the package
version = "0.1.0"    # the current version, obeying semver
authors = ["Geoffrey Guest <redeyedmars@gmail.com>"]

[dependencies]
failure = "0.1"
approx = "0.3.2"
